### PR TITLE
feat: add yarn.lock and travis.yml

### LINKED ISSUE #35: add continous integration
Once we have linting setup, it's important that we setup continous integration so that these rules are enforced before merging code. This way we can also run tests when a PR is submitted (once we have them). I suggest we use Travis CI (https://travis-ci.org/) as it's free for open source projects.

@JPSchellenberg i have requested access to integrate the CI.

### PR DESCRIPTION
**Pull request by defreek**
Closes #35

### CODE REVIEW

**Comment by defreek** [comment]
@JPSchellenberg the `build-server` command fails, although i'm on latest `develop` causing this PR to fail. Could you take a look at this?

**Comment by JPSchellenberg** [comment]
Do you have access to the build-log on travis?

**Comment by JPSchellenberg** [comment]
I have to clean up the package.json and get all the dependencies right. I think the build fails because yarn installs different dependencies than npm and the @types/react-dom dependencies cause the build to fail.

**Comment by JPSchellenberg** [comment]
https://github.com/yarnpkg/yarn/issues/4489
Typescript and yarn seem to have some Problems. The build works if I use 'npm install'. Maybe we should first add Travis and later on integrate yarn.. What do you think?

**Pull request merged**
