### PR TITLE
add linting configuration

### LINKED ISSUE #22: add editorconfig

### PR DESCRIPTION
**Pull request by defreek**
Closes #22 and #23 

This PR adds linting rules following the Airbnb styleguide (https://github.com/airbnb/javascript)
I also added formatting rules from Prettier, and i suggest that you install this for your IDE as well (https://prettier.io/docs/en/editors.html) this way we can ensure we have the same code formatting throughout the repo.

@JPSchellenberg the webpack PR should be merged before this one. When you checkout this PR, you will notice that there are alot of new linting errors being reported. We should fix those in this PR (and ideally before any other changes you make in `develop`)

### CODE REVIEW

**Comment by JPSchellenberg** [comment]
somehow travis does neither fail nor succeed.. I can not find PR #34 in the pull-request list of travis. 
And I can not merge develop into this branch again. Do you have any ideas why? Maybe we should just make a new PR..

**Comment by JPSchellenberg** [comment]
Nevermind.. i merged it locally. I still have to learn a lot about git & GitHub..

**Comment by JPSchellenberg** [comment]
I made one small adjustment to the linting-rules: snake_case is now allowed in variable-names, because the database (couchdb) auto assigns the id to the _id-field. We would always have linting-errors when we access the id in the _id field. Or is there a work-around?

**Comment by JPSchellenberg** [comment]
I dont see any lining-errors when I run the webpack-build. Maybe the tslint-loader has to be configured? (https://www.npmjs.com/package/tslint-loader) 
Do you think the build should fail if there are linting-errors? With travis it would prevent non-conform code to leak in :smile:

**Comment by defreek** [comment]
I updated the webpack build to include tslint. Right now it only generates warnings and will not fail the build. When you set `emitErrors` to true in `shared.config.js`, then it will fail the build. I suggest that right now we merge this PR, then try to fix all the linting errors in subsequent PRs and then enable the fail on error.

**Pull request merged**
