### PR TITLE
feat: webpack2

### LINKED ISSUE #10: update to webpack2 and clean config

### PR DESCRIPTION
**Pull request by defreek**
Closes #10 

@JPSchellenberg please check if everything still works as expected, cause i ommited alot from the config while the build still works so i assume the extra loaders for example are not needed.

### CODE REVIEW

**Comment by JPSchellenberg** [comment]
Thank you! Everything compiles fine. It seems that webpack3 does not need all the loaders.. But you omitted the devServer-config, which proxies the api-calls to the server. I tried to add it but then I get an error with the hot-reloading-module. Do you have any ideas how to integrate the proxy? And we need to inject the version somehow. I did it by using this plugin:
```new webpack.DefinePlugin({
  'process.env':{
    'NODE_ENV': JSON.stringify( process.env.NODE_ENV ),
    'VERSION': JSON.stringify( version )
    }
})```

**Comment by defreek** [comment]
@JPSchellenberg i re-added the proxy and version injection

**Comment by JPSchellenberg** [comment]
it works when I remove the `hot: true` config from devServer. Otherwise I get this: 
screen shot 2017-11-12 at 19 41 54

**Comment by JPSchellenberg** [comment]
One last thing before merging this PR: the historyApiFallback no longer defaults to index.html. So when reloading a route like /admin/groups you get an 404 instead of the index.html.

screen shot 2017-11-12 at 19 48 35

**Comment by defreek** [comment]
We have to use `webpack-dev-server --hot --inline` to use HMR with this version of webpack, i'll add this. I will also add some more optimizations for different node envs.

**Comment by defreek** [comment]
I added different configs for dev and prod, so prod is now more optimized. The bug you mentioned is also fixed.

**Pull request merged**
